kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: notes-app
  labels:
    app: notes-app
spec:
  triggers:
  - type: ConfigChange 
  - imageChangeParams:
      automatic: true
      containerNames:
      - notes-app
      from:
        kind: ImageStreamTag
        name: notes-app:latest
    type: ImageChange
  replicas: 1
  selector:
    app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
        