kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: notes-app
  labels:
    app: notes-app
spec:
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: "https://github.com/azza1998/Notes-apps.git"
      ref: master
    contextDir: app
  output:
    to:
      kind: ImageStreamTag
      name: notes-app:latest

