kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: notes-app
  labels:
    app: notes-app
spec:
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: "https://github.com/azza1998/Notes-apps.git"
      ref: main
    contextDir: app
  output:
    to:
      kind: DockerImage
      name: "172.30.48.47:5000/notes-app:latest"
